# Generated by Django 3.2.5 on 2021-07-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d1', models.CharField(max_length=200)),
                ('d2', models.CharField(max_length=200)),
            ],
        ),
    ]
